/* CVS $Id: $ */
package net.opentechnology.triki.schema; 
import org.apache.jena.rdf.model.*;
import org.apache.jena.ontology.*;
 
/**
 * Vocabulary definitions from src/main/resources/rdf/dcterms.rdf 
 * @author Auto-generated by schemagen on 28 May 2019 14:26 
 */
public class Dcterms {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/dc/terms/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>A summary of the resource.</p> */
    public static final OntProperty abstract_ = m_model.createOntProperty( "http://purl.org/dc/terms/abstract" );
    
    /** <p>Information about who can access the resource or an indication of its security 
     *  status.</p>
     */
    public static final OntProperty accessRights = m_model.createOntProperty( "http://purl.org/dc/terms/accessRights" );
    
    /** <p>The method by which items are added to a collection.</p> */
    public static final OntProperty accrualMethod = m_model.createOntProperty( "http://purl.org/dc/terms/accrualMethod" );
    
    /** <p>The frequency with which items are added to a collection.</p> */
    public static final OntProperty accrualPeriodicity = m_model.createOntProperty( "http://purl.org/dc/terms/accrualPeriodicity" );
    
    /** <p>The policy governing the addition of items to a collection.</p> */
    public static final OntProperty accrualPolicy = m_model.createOntProperty( "http://purl.org/dc/terms/accrualPolicy" );
    
    /** <p>An alternative name for the resource.</p> */
    public static final OntProperty alternative = m_model.createOntProperty( "http://purl.org/dc/terms/alternative" );
    
    /** <p>A class of entity for whom the resource is intended or useful.</p> */
    public static final OntProperty audience = m_model.createOntProperty( "http://purl.org/dc/terms/audience" );
    
    /** <p>Date (often a range) that the resource became or will become available.</p> */
    public static final OntProperty available = m_model.createOntProperty( "http://purl.org/dc/terms/available" );
    
    /** <p>A bibliographic reference for the resource.</p> */
    public static final OntProperty bibliographicCitation = m_model.createOntProperty( "http://purl.org/dc/terms/bibliographicCitation" );
    
    /** <p>An established standard to which the described resource conforms.</p> */
    public static final OntProperty conformsTo = m_model.createOntProperty( "http://purl.org/dc/terms/conformsTo" );
    
    /** <p>An entity responsible for making contributions to the resource.</p> */
    public static final OntProperty contributor = m_model.createOntProperty( "http://purl.org/dc/terms/contributor" );
    
    /** <p>The spatial or temporal topic of the resource, the spatial applicability of 
     *  the resource, or the jurisdiction under which the resource is relevant.</p>
     */
    public static final OntProperty coverage = m_model.createOntProperty( "http://purl.org/dc/terms/coverage" );
    
    /** <p>Date of creation of the resource.</p> */
    public static final OntProperty created = m_model.createOntProperty( "http://purl.org/dc/terms/created" );
    
    /** <p>An entity primarily responsible for making the resource.</p> */
    public static final OntProperty creator = m_model.createOntProperty( "http://purl.org/dc/terms/creator" );
    
    /** <p>A point or period of time associated with an event in the lifecycle of the 
     *  resource.</p>
     */
    public static final OntProperty date = m_model.createOntProperty( "http://purl.org/dc/terms/date" );
    
    /** <p>Date of acceptance of the resource.</p> */
    public static final OntProperty dateAccepted = m_model.createOntProperty( "http://purl.org/dc/terms/dateAccepted" );
    
    /** <p>Date of copyright.</p> */
    public static final OntProperty dateCopyrighted = m_model.createOntProperty( "http://purl.org/dc/terms/dateCopyrighted" );
    
    /** <p>Date of submission of the resource.</p> */
    public static final OntProperty dateSubmitted = m_model.createOntProperty( "http://purl.org/dc/terms/dateSubmitted" );
    
    /** <p>An account of the resource.</p> */
    public static final OntProperty description = m_model.createOntProperty( "http://purl.org/dc/terms/description" );
    
    /** <p>A class of entity, defined in terms of progression through an educational 
     *  or training context, for which the described resource is intended.</p>
     */
    public static final OntProperty educationLevel = m_model.createOntProperty( "http://purl.org/dc/terms/educationLevel" );
    
    /** <p>The size or duration of the resource.</p> */
    public static final OntProperty extent = m_model.createOntProperty( "http://purl.org/dc/terms/extent" );
    
    /** <p>The file format, physical medium, or dimensions of the resource.</p> */
    public static final OntProperty format = m_model.createOntProperty( "http://purl.org/dc/terms/format" );
    
    /** <p>A related resource that is substantially the same as the pre-existing described 
     *  resource, but in another format.</p>
     */
    public static final OntProperty hasFormat = m_model.createOntProperty( "http://purl.org/dc/terms/hasFormat" );
    
    /** <p>A related resource that is included either physically or logically in the 
     *  described resource.</p>
     */
    public static final OntProperty hasPart = m_model.createOntProperty( "http://purl.org/dc/terms/hasPart" );
    
    /** <p>A related resource that is a version, edition, or adaptation of the described 
     *  resource.</p>
     */
    public static final OntProperty hasVersion = m_model.createOntProperty( "http://purl.org/dc/terms/hasVersion" );
    
    /** <p>An unambiguous reference to the resource within a given context.</p> */
    public static final OntProperty identifier = m_model.createOntProperty( "http://purl.org/dc/terms/identifier" );
    
    /** <p>A process, used to engender knowledge, attitudes and skills, that the described 
     *  resource is designed to support.</p>
     */
    public static final OntProperty instructionalMethod = m_model.createOntProperty( "http://purl.org/dc/terms/instructionalMethod" );
    
    /** <p>A related resource that is substantially the same as the described resource, 
     *  but in another format.</p>
     */
    public static final OntProperty isFormatOf = m_model.createOntProperty( "http://purl.org/dc/terms/isFormatOf" );
    
    /** <p>A related resource in which the described resource is physically or logically 
     *  included.</p>
     */
    public static final OntProperty isPartOf = m_model.createOntProperty( "http://purl.org/dc/terms/isPartOf" );
    
    /** <p>A related resource that references, cites, or otherwise points to the described 
     *  resource.</p>
     */
    public static final OntProperty isReferencedBy = m_model.createOntProperty( "http://purl.org/dc/terms/isReferencedBy" );
    
    /** <p>A related resource that supplants, displaces, or supersedes the described 
     *  resource.</p>
     */
    public static final OntProperty isReplacedBy = m_model.createOntProperty( "http://purl.org/dc/terms/isReplacedBy" );
    
    /** <p>A related resource that requires the described resource to support its function, 
     *  delivery, or coherence.</p>
     */
    public static final OntProperty isRequiredBy = m_model.createOntProperty( "http://purl.org/dc/terms/isRequiredBy" );
    
    /** <p>A related resource of which the described resource is a version, edition, 
     *  or adaptation.</p>
     */
    public static final OntProperty isVersionOf = m_model.createOntProperty( "http://purl.org/dc/terms/isVersionOf" );
    
    /** <p>Date of formal issuance (e.g., publication) of the resource.</p> */
    public static final OntProperty issued = m_model.createOntProperty( "http://purl.org/dc/terms/issued" );
    
    /** <p>A language of the resource.</p> */
    public static final OntProperty language = m_model.createOntProperty( "http://purl.org/dc/terms/language" );
    
    /** <p>A legal document giving official permission to do something with the resource.</p> */
    public static final OntProperty license = m_model.createOntProperty( "http://purl.org/dc/terms/license" );
    
    /** <p>An entity that mediates access to the resource and for whom the resource is 
     *  intended or useful.</p>
     */
    public static final OntProperty mediator = m_model.createOntProperty( "http://purl.org/dc/terms/mediator" );
    
    /** <p>The material or physical carrier of the resource.</p> */
    public static final OntProperty medium = m_model.createOntProperty( "http://purl.org/dc/terms/medium" );
    
    /** <p>Date on which the resource was changed.</p> */
    public static final OntProperty modified = m_model.createOntProperty( "http://purl.org/dc/terms/modified" );
    
    /** <p>A statement of any changes in ownership and custody of the resource since 
     *  its creation that are significant for its authenticity, integrity, and interpretation.</p>
     */
    public static final OntProperty provenance = m_model.createOntProperty( "http://purl.org/dc/terms/provenance" );
    
    /** <p>An entity responsible for making the resource available.</p> */
    public static final OntProperty publisher = m_model.createOntProperty( "http://purl.org/dc/terms/publisher" );
    
    /** <p>A related resource that is referenced, cited, or otherwise pointed to by the 
     *  described resource.</p>
     */
    public static final OntProperty references = m_model.createOntProperty( "http://purl.org/dc/terms/references" );
    
    /** <p>A related resource.</p> */
    public static final OntProperty relation = m_model.createOntProperty( "http://purl.org/dc/terms/relation" );
    
    /** <p>A related resource that is supplanted, displaced, or superseded by the described 
     *  resource.</p>
     */
    public static final OntProperty replaces = m_model.createOntProperty( "http://purl.org/dc/terms/replaces" );
    
    /** <p>A related resource that is required by the described resource to support its 
     *  function, delivery, or coherence.</p>
     */
    public static final OntProperty requires = m_model.createOntProperty( "http://purl.org/dc/terms/requires" );
    
    /** <p>Information about rights held in and over the resource.</p> */
    public static final OntProperty rights = m_model.createOntProperty( "http://purl.org/dc/terms/rights" );
    
    /** <p>A person or organization owning or managing rights over the resource.</p> */
    public static final OntProperty rightsHolder = m_model.createOntProperty( "http://purl.org/dc/terms/rightsHolder" );
    
    /** <p>A related resource from which the described resource is derived.</p> */
    public static final OntProperty source = m_model.createOntProperty( "http://purl.org/dc/terms/source" );
    
    /** <p>Spatial characteristics of the resource.</p> */
    public static final OntProperty spatial = m_model.createOntProperty( "http://purl.org/dc/terms/spatial" );
    
    /** <p>The topic of the resource.</p> */
    public static final OntProperty subject = m_model.createOntProperty( "http://purl.org/dc/terms/subject" );
    
    /** <p>A list of subunits of the resource.</p> */
    public static final OntProperty tableOfContents = m_model.createOntProperty( "http://purl.org/dc/terms/tableOfContents" );
    
    /** <p>Temporal characteristics of the resource.</p> */
    public static final OntProperty temporal = m_model.createOntProperty( "http://purl.org/dc/terms/temporal" );
    
    public static final OntProperty title = m_model.createOntProperty( "http://purl.org/dc/terms/title" );
    
    /** <p>The nature or genre of the resource.</p> */
    public static final OntProperty type = m_model.createOntProperty( "http://purl.org/dc/terms/type" );
    
    /** <p>Date (often a range) of validity of a resource.</p> */
    public static final OntProperty valid = m_model.createOntProperty( "http://purl.org/dc/terms/valid" );
    
    /** <p>A resource that acts or has the power to act.</p> */
    public static final OntClass Agent = m_model.createClass( "http://purl.org/dc/terms/Agent" );
    
    /** <p>A group of agents.</p> */
    public static final OntClass AgentClass = m_model.createClass( "http://purl.org/dc/terms/AgentClass" );
    
    /** <p>A book, article, or other documentary resource.</p> */
    public static final OntClass BibliographicResource = m_model.createClass( "http://purl.org/dc/terms/BibliographicResource" );
    
    public static final OntClass Collection = m_model.createClass( "http://purl.org/dc/terms/Collection" );
    
    /** <p>A digital resource format.</p> */
    public static final OntClass FileFormat = m_model.createClass( "http://purl.org/dc/terms/FileFormat" );
    
    /** <p>A rate at which something recurs.</p> */
    public static final OntClass Frequency = m_model.createClass( "http://purl.org/dc/terms/Frequency" );
    
    /** <p>The extent or range of judicial, law enforcement, or other authority.</p> */
    public static final OntClass Jurisdiction = m_model.createClass( "http://purl.org/dc/terms/Jurisdiction" );
    
    /** <p>A legal document giving official permission to do something with a Resource.</p> */
    public static final OntClass LicenseDocument = m_model.createClass( "http://purl.org/dc/terms/LicenseDocument" );
    
    /** <p>A system of signs, symbols, sounds, gestures, or rules used in communication.</p> */
    public static final OntClass LinguisticSystem = m_model.createClass( "http://purl.org/dc/terms/LinguisticSystem" );
    
    /** <p>A spatial region or named place.</p> */
    public static final OntClass Location = m_model.createClass( "http://purl.org/dc/terms/Location" );
    
    /** <p>A location, period of time, or jurisdiction.</p> */
    public static final OntClass LocationPeriodOrJurisdiction = m_model.createClass( "http://purl.org/dc/terms/LocationPeriodOrJurisdiction" );
    
    /** <p>A file format or physical medium.</p> */
    public static final OntClass MediaType = m_model.createClass( "http://purl.org/dc/terms/MediaType" );
    
    /** <p>A media type or extent.</p> */
    public static final OntClass MediaTypeOrExtent = m_model.createClass( "http://purl.org/dc/terms/MediaTypeOrExtent" );
    
    /** <p>A method by which resources are added to a collection.</p> */
    public static final OntClass MethodOfAccrual = m_model.createClass( "http://purl.org/dc/terms/MethodOfAccrual" );
    
    /** <p>A process that is used to engender knowledge, attitudes, and skills.</p> */
    public static final OntClass MethodOfInstruction = m_model.createClass( "http://purl.org/dc/terms/MethodOfInstruction" );
    
    /** <p>An interval of time that is named or defined by its start and end dates.</p> */
    public static final OntClass PeriodOfTime = m_model.createClass( "http://purl.org/dc/terms/PeriodOfTime" );
    
    /** <p>A physical material or carrier.</p> */
    public static final OntClass PhysicalMedium = m_model.createClass( "http://purl.org/dc/terms/PhysicalMedium" );
    
    /** <p>A material thing.</p> */
    public static final OntClass PhysicalResource = m_model.createClass( "http://purl.org/dc/terms/PhysicalResource" );
    
    /** <p>A plan or course of action by an authority, intended to influence and determine 
     *  decisions, actions, and other matters.</p>
     */
    public static final OntClass Policy = m_model.createClass( "http://purl.org/dc/terms/Policy" );
    
    /** <p>A statement of any changes in ownership and custody of a resource since its 
     *  creation that are significant for its authenticity, integrity, and interpretation.</p>
     */
    public static final OntClass ProvenanceStatement = m_model.createClass( "http://purl.org/dc/terms/ProvenanceStatement" );
    
    /** <p>A statement about the intellectual property rights (IPR) held in or over a 
     *  Resource, a legal document giving official permission to do something with 
     *  a resource, or a statement about access rights.</p>
     */
    public static final OntClass RightsStatement = m_model.createClass( "http://purl.org/dc/terms/RightsStatement" );
    
    /** <p>A dimension or extent, or a time taken to play or execute.</p> */
    public static final OntClass SizeOrDuration = m_model.createClass( "http://purl.org/dc/terms/SizeOrDuration" );
    
    /** <p>A basis for comparison; a reference point against which other things can be 
     *  evaluated.</p>
     */
    public static final OntClass Standard = m_model.createClass( "http://purl.org/dc/terms/Standard" );
    
    /** <p>The set of classes specified by the DCMI Type Vocabulary, used to categorize 
     *  the nature or genre of the resource.</p>
     */
    public static final Individual DCMIType = m_model.createIndividual( "http://purl.org/dc/terms/DCMIType", m_model.createClass( "http://purl.org/dc/dcam/VocabularyEncodingScheme" ) );
    
    /** <p>The set of conceptual resources specified by the Dewey Decimal Classification.</p> */
    public static final Individual DDC = m_model.createIndividual( "http://purl.org/dc/terms/DDC", m_model.createClass( "http://purl.org/dc/dcam/VocabularyEncodingScheme" ) );
    
    /** <p>The set of media types specified by the Internet Assigned Numbers Authority.</p> */
    public static final Individual IMT = m_model.createIndividual( "http://purl.org/dc/terms/IMT", m_model.createClass( "http://purl.org/dc/dcam/VocabularyEncodingScheme" ) );
    
    /** <p>The set of conceptual resources specified by the Library of Congress Classification.</p> */
    public static final Individual LCC = m_model.createIndividual( "http://purl.org/dc/terms/LCC", m_model.createClass( "http://purl.org/dc/dcam/VocabularyEncodingScheme" ) );
    
    /** <p>The set of labeled concepts specified by the Library of Congress Subject Headings.</p> */
    public static final Individual LCSH = m_model.createIndividual( "http://purl.org/dc/terms/LCSH", m_model.createClass( "http://purl.org/dc/dcam/VocabularyEncodingScheme" ) );
    
    /** <p>The set of labeled concepts specified by the Medical Subject Headings.</p> */
    public static final Individual MESH = m_model.createIndividual( "http://purl.org/dc/terms/MESH", m_model.createClass( "http://purl.org/dc/dcam/VocabularyEncodingScheme" ) );
    
    /** <p>The set of conceptual resources specified by the National Library of Medicine 
     *  Classification.</p>
     */
    public static final Individual NLM = m_model.createIndividual( "http://purl.org/dc/terms/NLM", m_model.createClass( "http://purl.org/dc/dcam/VocabularyEncodingScheme" ) );
    
    /** <p>The set of places specified by the Getty Thesaurus of Geographic Names.</p> */
    public static final Individual TGN = m_model.createIndividual( "http://purl.org/dc/terms/TGN", m_model.createClass( "http://purl.org/dc/dcam/VocabularyEncodingScheme" ) );
    
    /** <p>The set of conceptual resources specified by the Universal Decimal Classification.</p> */
    public static final Individual UDC = m_model.createIndividual( "http://purl.org/dc/terms/UDC", m_model.createClass( "http://purl.org/dc/dcam/VocabularyEncodingScheme" ) );
    
    /** <p>The set of regions in space defined by their geographic coordinates according 
     *  to the DCMI Box Encoding Scheme.</p>
     */
    public static final Resource Box = m_model.createResource( "http://purl.org/dc/terms/Box" );
    
    /** <p>The set of codes listed in ISO 3166-1 for the representation of names of countries.</p> */
    public static final Resource ISO3166 = m_model.createResource( "http://purl.org/dc/terms/ISO3166" );
    
    /** <p>The three-letter alphabetic codes listed in ISO639-2 for the representation 
     *  of names of languages.</p>
     */
    public static final Resource ISO639_2 = m_model.createResource( "http://purl.org/dc/terms/ISO639-2" );
    
    /** <p>The set of three-letter codes listed in ISO 639-3 for the representation of 
     *  names of languages.</p>
     */
    public static final Resource ISO639_3 = m_model.createResource( "http://purl.org/dc/terms/ISO639-3" );
    
    /** <p>The set of time intervals defined by their limits according to the DCMI Period 
     *  Encoding Scheme.</p>
     */
    public static final Resource Period = m_model.createResource( "http://purl.org/dc/terms/Period" );
    
    /** <p>The set of points in space defined by their geographic coordinates according 
     *  to the DCMI Point Encoding Scheme.</p>
     */
    public static final Resource Point = m_model.createResource( "http://purl.org/dc/terms/Point" );
    
    /** <p>The set of tags, constructed according to RFC 1766, for the identification 
     *  of languages.</p>
     */
    public static final Resource RFC1766 = m_model.createResource( "http://purl.org/dc/terms/RFC1766" );
    
    /** <p>The set of tags constructed according to RFC 3066 for the identification of 
     *  languages.</p>
     */
    public static final Resource RFC3066 = m_model.createResource( "http://purl.org/dc/terms/RFC3066" );
    
    /** <p>The set of tags constructed according to RFC 4646 for the identification of 
     *  languages.</p>
     */
    public static final Resource RFC4646 = m_model.createResource( "http://purl.org/dc/terms/RFC4646" );
    
    /** <p>The set of identifiers constructed according to the generic syntax for Uniform 
     *  Resource Identifiers as specified by the Internet Engineering Task Force.</p>
     */
    public static final Resource URI = m_model.createResource( "http://purl.org/dc/terms/URI" );
    
    /** <p>The set of dates and times constructed according to the W3C Date and Time 
     *  Formats Specification.</p>
     */
    public static final Resource W3CDTF = m_model.createResource( "http://purl.org/dc/terms/W3CDTF" );
    
}
