/* CVS $Id: $ */
package net.opentechnology.triki.schema; 
import org.apache.jena.rdf.model.*;
import org.apache.jena.ontology.*;
 
/**
 * Vocabulary definitions from src/main/resources/rdf/rdfbase.rdf 
 * @author Auto-generated by schemagen on 28 May 2019 14:26 
 */
public class Rdfbase {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.w3.org/1999/02/22-rdf-syntax-ns#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final ObjectProperty differentFrom = m_model.createObjectProperty( "http://www.w3.org/2002/07/owl#differentFrom" );
    
    public static final ObjectProperty disjointWith = m_model.createObjectProperty( "http://www.w3.org/2002/07/owl#disjointWith" );
    
    public static final ObjectProperty sameAs = m_model.createObjectProperty( "http://www.w3.org/2002/07/owl#sameAs" );
    
    public static final OntProperty description = m_model.createOntProperty( "http://purl.org/dc/elements/1.1/description" );
    
    public static final OntProperty title = m_model.createOntProperty( "http://purl.org/dc/elements/1.1/title" );
    
    /** <p>The first item in the subject RDF list.</p> */
    public static final OntProperty first = m_model.createOntProperty( "http://www.w3.org/1999/02/22-rdf-syntax-ns#first" );
    
    /** <p>The object of the subject RDF statement.</p> */
    public static final OntProperty object = m_model.createOntProperty( "http://www.w3.org/1999/02/22-rdf-syntax-ns#object" );
    
    /** <p>The predicate of the subject RDF statement.</p> */
    public static final OntProperty predicate = m_model.createOntProperty( "http://www.w3.org/1999/02/22-rdf-syntax-ns#predicate" );
    
    /** <p>The rest of the subject RDF list after the first item.</p> */
    public static final OntProperty rest = m_model.createOntProperty( "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest" );
    
    /** <p>The subject of the subject RDF statement.</p> */
    public static final OntProperty subject = m_model.createOntProperty( "http://www.w3.org/1999/02/22-rdf-syntax-ns#subject" );
    
    /** <p>The subject is an instance of a class.</p> */
    public static final OntProperty type = m_model.createOntProperty( "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" );
    
    /** <p>Idiomatic property used for structured values.</p> */
    public static final OntProperty value = m_model.createOntProperty( "http://www.w3.org/1999/02/22-rdf-syntax-ns#value" );
    
    public static final OntProperty comment = m_model.createOntProperty( "http://www.w3.org/2000/01/rdf-schema#comment" );
    
    public static final OntProperty domain = m_model.createOntProperty( "http://www.w3.org/2000/01/rdf-schema#domain" );
    
    public static final OntProperty isDefinedBy = m_model.createOntProperty( "http://www.w3.org/2000/01/rdf-schema#isDefinedBy" );
    
    public static final OntProperty label = m_model.createOntProperty( "http://www.w3.org/2000/01/rdf-schema#label" );
    
    public static final OntProperty range = m_model.createOntProperty( "http://www.w3.org/2000/01/rdf-schema#range" );
    
    public static final OntProperty seeAlso = m_model.createOntProperty( "http://www.w3.org/2000/01/rdf-schema#seeAlso" );
    
    public static final OntProperty subClassOf = m_model.createOntProperty( "http://www.w3.org/2000/01/rdf-schema#subClassOf" );
    
    public static final OntProperty subPropertyOf = m_model.createOntProperty( "http://www.w3.org/2000/01/rdf-schema#subPropertyOf" );
    
    public static final OntProperty backwardCompatibleWith = m_model.createOntProperty( "http://www.w3.org/2002/07/owl#backwardCompatibleWith" );
    
    public static final OntProperty equivalentClass = m_model.createOntProperty( "http://www.w3.org/2002/07/owl#equivalentClass" );
    
    public static final OntProperty imports = m_model.createOntProperty( "http://www.w3.org/2002/07/owl#imports" );
    
    public static final OntProperty incompatibleWith = m_model.createOntProperty( "http://www.w3.org/2002/07/owl#incompatibleWith" );
    
    public static final OntProperty intersectionOf = m_model.createOntProperty( "http://www.w3.org/2002/07/owl#intersectionOf" );
    
    public static final OntProperty onProperty = m_model.createOntProperty( "http://www.w3.org/2002/07/owl#onProperty" );
    
    public static final OntProperty oneOf = m_model.createOntProperty( "http://www.w3.org/2002/07/owl#oneOf" );
    
    public static final OntProperty priorVersion = m_model.createOntProperty( "http://www.w3.org/2002/07/owl#priorVersion" );
    
    /** <p>The class of containers of alternatives.</p> */
    public static final OntClass Alt = m_model.createClass( "http://www.w3.org/1999/02/22-rdf-syntax-ns#Alt" );
    
    /** <p>The class of unordered containers.</p> */
    public static final OntClass Bag = m_model.createClass( "http://www.w3.org/1999/02/22-rdf-syntax-ns#Bag" );
    
    /** <p>The class of RDF Lists.</p> */
    public static final OntClass List = m_model.createClass( "http://www.w3.org/1999/02/22-rdf-syntax-ns#List" );
    
    /** <p>The class of RDF properties.</p> */
    public static final OntClass Property = m_model.createClass( "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property" );
    
    /** <p>The class of ordered containers.</p> */
    public static final OntClass Seq = m_model.createClass( "http://www.w3.org/1999/02/22-rdf-syntax-ns#Seq" );
    
    /** <p>The class of RDF statements.</p> */
    public static final OntClass Statement = m_model.createClass( "http://www.w3.org/1999/02/22-rdf-syntax-ns#Statement" );
    
    /** <p>The class of plain (i.e. untyped) literal values.</p> */
    public static final Resource PlainLiteral = m_model.createResource( "http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral" );
    
    /** <p>The class of XML literal values.</p> */
    public static final Resource XMLLiteral = m_model.createResource( "http://www.w3.org/1999/02/22-rdf-syntax-ns#XMLLiteral" );
    
}
