/* CVS $Id: $ */
package net.opentechnology.triki.schema; 
import org.apache.jena.rdf.model.*;
import org.apache.jena.ontology.*;
 
/**
 * Vocabulary definitions from src/main/resources/rdf/review.rdf 
 * @author Auto-generated by schemagen on 28 May 2019 14:26 
 */
public class Review {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/stuff/rev#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>The commenter on the review</p> */
    public static final ObjectProperty commenter = m_model.createObjectProperty( "http://purl.org/stuff/rev#commenter" );
    
    /** <p>Used to associate a review with a comment on the review</p> */
    public static final ObjectProperty hasComment = m_model.createObjectProperty( "http://purl.org/stuff/rev#hasComment" );
    
    /** <p>Associates a review with a feedback on the review</p> */
    public static final ObjectProperty hasFeedback = m_model.createObjectProperty( "http://purl.org/stuff/rev#hasFeedback" );
    
    /** <p>Associates a work with a a review</p> */
    public static final ObjectProperty hasReview = m_model.createObjectProperty( "http://purl.org/stuff/rev#hasReview" );
    
    /** <p>The person that has written the review</p> */
    public static final ObjectProperty reviewer = m_model.createObjectProperty( "http://purl.org/stuff/rev#reviewer" );
    
    /** <p>Number of positive usefulness votes (integer)</p> */
    public static final DatatypeProperty positiveVotes = m_model.createDatatypeProperty( "http://purl.org/stuff/rev#positiveVotes" );
    
    /** <p>A numeric value</p> */
    public static final DatatypeProperty rating = m_model.createDatatypeProperty( "http://purl.org/stuff/rev#rating" );
    
    /** <p>The text of the review</p> */
    public static final DatatypeProperty text = m_model.createDatatypeProperty( "http://purl.org/stuff/rev#text" );
    
    /** <p>The title of the review</p> */
    public static final DatatypeProperty title = m_model.createDatatypeProperty( "http://purl.org/stuff/rev#title" );
    
    /** <p>Number of usefulness votes (integer)</p> */
    public static final DatatypeProperty totalVotes = m_model.createDatatypeProperty( "http://purl.org/stuff/rev#totalVotes" );
    
    /** <p>The type of media of a work under review</p> */
    public static final DatatypeProperty type = m_model.createDatatypeProperty( "http://purl.org/stuff/rev#type" );
    
    /** <p>A numeric value</p> */
    public static final OntProperty maxRating = m_model.createOntProperty( "http://purl.org/stuff/rev#maxRating" );
    
    /** <p>A numeric value</p> */
    public static final OntProperty minRating = m_model.createOntProperty( "http://purl.org/stuff/rev#minRating" );
    
    /** <p>A comment on a review</p> */
    public static final OntClass Comment = m_model.createClass( "http://purl.org/stuff/rev#Comment" );
    
    /** <p>Feedback on the review. Expresses whether the review was useful or not</p> */
    public static final OntClass Feedback = m_model.createClass( "http://purl.org/stuff/rev#Feedback" );
    
    /** <p>A review of an work</p> */
    public static final OntClass Review = m_model.createClass( "http://purl.org/stuff/rev#Review" );
    
}
