/* CVS $Id: $ */
package net.opentechnology.triki.schema; 
import org.apache.jena.rdf.model.*;
import org.apache.jena.ontology.*;
 
/**
 * Vocabulary definitions from src/main/resources/rdf/rss.rdf 
 * @author Auto-generated by schemagen on 28 May 2019 14:26 
 */
public class Rss {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/rss/1.0/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>A short text description of the subject.</p> */
    public static final OntProperty description = m_model.createOntProperty( "http://purl.org/rss/1.0/description" );
    
    /** <p>Points to a list of rss:item elements that are members of the subject channel.</p> */
    public static final OntProperty items = m_model.createOntProperty( "http://purl.org/rss/1.0/items" );
    
    /** <p>The URL to which an HTML rendering of the subject will link.</p> */
    public static final OntProperty link = m_model.createOntProperty( "http://purl.org/rss/1.0/link" );
    
    /** <p>The text input field's (variable) name.</p> */
    public static final OntProperty name = m_model.createOntProperty( "http://purl.org/rss/1.0/name" );
    
    /** <p>A descriptive title for the channel.</p> */
    public static final OntProperty title = m_model.createOntProperty( "http://purl.org/rss/1.0/title" );
    
    /** <p>The URL of the image to used in the 'src' attribute of the channel's image 
     *  tag when rendered as HTML.</p>
     */
    public static final OntProperty url = m_model.createOntProperty( "http://purl.org/rss/1.0/url" );
    
    /** <p>An RSS information channel.</p> */
    public static final OntClass channel = m_model.createClass( "http://purl.org/rss/1.0/channel" );
    
    /** <p>An RSS image.</p> */
    public static final OntClass image = m_model.createClass( "http://purl.org/rss/1.0/image" );
    
    /** <p>An RSS item.</p> */
    public static final OntClass item = m_model.createClass( "http://purl.org/rss/1.0/item" );
    
    /** <p>An RSS text input.</p> */
    public static final OntClass textinput = m_model.createClass( "http://purl.org/rss/1.0/textinput" );
    
}
