/* CVS $Id: $ */
package net.opentechnology.triki.schema; 
import org.apache.jena.rdf.model.*;
import org.apache.jena.ontology.*;
 
/**
 * Vocabulary definitions from src/main/resources/rdf/triki.rdf 
 * @author Auto-generated by schemagen on 28 May 2019 14:26 
 */
public class Triki {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.opentechnology.net/triki/0.1/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>Triki content</p> */
    public static final OntProperty content = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/content" );
    
    /** <p>Date format</p> */
    public static final OntProperty dateformat = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/dateformat" );
    
    /** <p>Feed type</p> */
    public static final OntProperty feedtype = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/feedtype" );
    
    /** <p>Feed URl</p> */
    public static final OntProperty feedurl = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/feedurl" );
    
    /** <p>Home page after login</p> */
    public static final OntProperty home = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/home" );
    
    /** <p>IndieAuth ID</p> */
    public static final OntProperty id = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/id" );
    
    /** <p>Include external content</p> */
    public static final OntProperty include = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/include" );
    
    /** <p>Index page.</p> */
    public static final OntProperty index = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/index" );
    
    /** <p>Item parser</p> */
    public static final OntProperty itemParser = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/itemParser" );
    
    /** <p>Keywords</p> */
    public static final OntProperty keywords = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/keywords" );
    
    /** <p>Name of groovy closure to find link</p> */
    public static final OntProperty linkref = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/linkref" );
    
    /** <p>Login</p> */
    public static final OntProperty login = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/login" );
    
    /** <p>Max cache age</p> */
    public static final OntProperty maxage = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/maxage" );
    
    /** <p>OAuth auth endpoint</p> */
    public static final OntProperty oauthauthendpoint = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/oauthauthendpoint" );
    
    /** <p>OAuth client ID</p> */
    public static final OntProperty oauthclientid = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/oauthclientid" );
    
    /** <p>OAuth client secret</p> */
    public static final OntProperty oauthclientsecret = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/oauthclientsecret" );
    
    /** <p>OAuth scope</p> */
    public static final OntProperty oauthscope = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/oauthscope" );
    
    /** <p>OAuth token endpoint</p> */
    public static final OntProperty oauthtokenendpoint = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/oauthtokenendpoint" );
    
    /** <p>Natural ordering</p> */
    public static final OntProperty order = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/order" );
    
    /** <p>Page property</p> */
    public static final OntProperty pageProperty = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/pageProperty" );
    
    /** <p>Page type</p> */
    public static final OntProperty pageType = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/pageType" );
    
    /** <p>Page views</p> */
    public static final OntProperty pageViews = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/pageViews" );
    
    /** <p>SHA Password</p> */
    public static final OntProperty password = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/password" );
    
    /** <p>A property renderer name</p> */
    public static final OntProperty propertyrenderer = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/propertyrenderer" );
    
    /** <p>Refresh rateRefresh</p> */
    public static final OntProperty refresh = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/refresh" );
    
    /** <p>Access restriction</p> */
    public static final OntProperty restricted = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/restricted" );
    
    /** <p>Triki content</p> */
    public static final OntProperty setting = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/setting" );
    
    /** <p>Base Uri of the site</p> */
    public static final OntProperty siteUri = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/siteUri" );
    
    /** <p>Source</p> */
    public static final OntProperty source = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/source" );
    
    /** <p>SPARQL query</p> */
    public static final OntProperty sparql = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/sparql" );
    
    /** <p>Triki template</p> */
    public static final OntProperty template = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/template" );
    
    /** <p>Thumbnail Imagae</p> */
    public static final OntProperty thumbimg = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/thumbimg" );
    
    /** <p>Access unrestricted</p> */
    public static final OntProperty unrestricted = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/unrestricted" );
    
    /** <p>Web content</p> */
    public static final OntProperty webcontent = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/webcontent" );
    
    /** <p>Web Image</p> */
    public static final OntProperty webimg = m_model.createOntProperty( "http://www.opentechnology.net/triki/0.1/webimg" );
    
    /** <p>A triki blog.</p> */
    public static final OntClass Blog = m_model.createClass( "http://www.opentechnology.net/triki/0.1/Blog" );
    
    /** <p>Content Type for content</p> */
    public static final OntClass Content = m_model.createClass( "http://www.opentechnology.net/triki/0.1/Content" );
    
    /** <p>Feed type</p> */
    public static final OntClass Feed = m_model.createClass( "http://www.opentechnology.net/triki/0.1/Feed" );
    
    /** <p>An identify provider</p> */
    public static final OntClass IdentityProvider = m_model.createClass( "http://www.opentechnology.net/triki/0.1/IdentityProvider" );
    
    /** <p>Media Type for content</p> */
    public static final OntClass MediaType = m_model.createClass( "http://www.opentechnology.net/triki/0.1/MediaType" );
    
    /** <p>A note.</p> */
    public static final OntClass Note = m_model.createClass( "http://www.opentechnology.net/triki/0.1/Note" );
    
    /** <p>A page on a triki website</p> */
    public static final OntClass Page = m_model.createClass( "http://www.opentechnology.net/triki/0.1/Page" );
    
    /** <p>Vocabulary prefix used with templates</p> */
    public static final OntClass Prefix = m_model.createClass( "http://www.opentechnology.net/triki/0.1/Prefix" );
    
    /** <p>A page property</p> */
    public static final OntClass Property = m_model.createClass( "http://www.opentechnology.net/triki/0.1/Property" );
    
    /** <p>Setting Type for content</p> */
    public static final OntClass Setting = m_model.createClass( "http://www.opentechnology.net/triki/0.1/Setting" );
    
    /** <p>A page type</p> */
    public static final OntClass Type = m_model.createClass( "http://www.opentechnology.net/triki/0.1/Type" );
    
}
